### ISSUE TITLE
你好，可以大致说一下SASM的算法思想吗，没有找到论文，看代码有点糊涂的感觉谢谢

### ISSUE THREAD

**Issue by lalalagogogochong** [houliping/SASM#1]

**Comment by houliping** [comment]
https://zhuanlan.zhihu.com/p/461454563
论文不久之后就会公开，感谢对工作的关注，如再有困惑，可再联系我。谢谢




在2022年03月16日 ***@***.***> 写道：

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangxue0827** [comment]
https://www.aaai.org/AAAI22Papers/AAAI-2171.HouL.pdf
@lalalagogogochong

**Comment by lalalagogogochong** [comment]
> https://www.aaai.org/AAAI22Papers/AAAI-2171.HouL.pdf @lalalagogogochong

好的，谢谢你啦
