### ISSUE TITLE
关于sas_assigner.py中的导入包ops.point_justify报错

### ISSUE THREAD

**Issue by xc-chengdu** [houliping/SASM#3]
你好，感谢您的贡献。但是，我最近按照您给出的步骤复现您的方法时，from mmdet.ops.point_justify import pointsf 出现错误，我用的是torch1.3,mmcv==0.2.14,cuda10.0。您可以提供一下您的解决方案吗，谢谢。

**Comment by houliping** [comment]
可以贴一下具体报错的原因吗？

**Comment by xc-chengdu** [comment]
好的，这两天尝试着自己解决了一下，但是还是没有成功解决这个问题。具体的报错如下：

![微信图片_20220331180332](https://user-images.githubusercontent.com/72692177/161031332-d0ea58a4-30b9-4fa4-9217-59446a83299f.jpg)

**Comment by houliping** [comment]
已经上传了，你可以下载导入安装一下

**Comment by seacloud-0420** [comment]
@houliping 
I downloaded the point_justify folder and put it under folder mmdet/ops, but still reported this error. What do you mean by downloading and installing? How to install it?

**Comment by seacloud-0420** [comment]
@xc-chengdu 
Hi, has your problem been solved?

**Comment by goddd-szz** [comment]
@xc-chengdu 请问这个包需要安装到哪里
